version = 1

test_patterns = ["*/test/**"]

exclude_patterns = [
  "public/**,",
  "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[transformers]]
name = "standardjs"
enabled = true

[[transformers]]
name = "prettier"
enabled = true