version = 1

test_patterns = ["*/test/**"]

exclude_patterns = [
    "public/**,",
    "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]
  module_system = "es-modules"
  skip_doc_coverage = ["class-expression", "method-definition"]
  style_guide = "google"